//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heli.Scada.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public Engineer()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public int engineerid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
