//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heli.Scada.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installation
    {
        public Installation()
        {
            this.Measurement = new HashSet<Measurement>();
        }
    
        public int installationid { get; set; }
        public string serialno { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public string description { get; set; }
        public int customerid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Measurement> Measurement { get; set; }
    }
}
