//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heli.Scada.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement_Type
    {
        public Measurement_Type()
        {
            this.Measurement = new HashSet<Measurement>();
        }
    
        public int typeid { get; set; }
        public string description { get; set; }
        public decimal minvalue { get; set; }
        public decimal maxvalue { get; set; }
        public string unit { get; set; }
    
        public virtual ICollection<Measurement> Measurement { get; set; }
    }
}
