//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heli.Scada.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int measid { get; set; }
        public System.DateTime timestamp { get; set; }
        public int installationid { get; set; }
        public int typeid { get; set; }
        public decimal measurevalue { get; set; }
    
        public virtual Installation Installation { get; set; }
        public virtual Measurement_Type Measurement_Type { get; set; }
    }
}
